---
- name: Fetching Jetbrains Toolbox latest version download link
  uri:
    url: https://data.services.jetbrains.com/products/releases?code=TBA&latest=true&type=release
    method: GET
    return_content: yes
    status_code: 200
    body_format: json
  register: data

- name: Installing Jetbrains Toolbox
  become: yes
  unarchive:
    remote_src: yes
    src: "{{ data.json.TBA[0].downloads.linux.link }}"
    dest: /opt/