---
- include: update_status.yml
  vars:
    text: Installing Applications

- include_tasks: multimedia_plugins.yml
- include_tasks: google_chrome.yml
- include_tasks: jetbrains_toolbox.yml
- include_tasks: sublime_text.yml
- include_tasks: vscode.yml
- include_tasks: starship.yml

- name: Installing Flatpak Applications
  flatpak:
    remote: flathub
    state: present
    method: user
    name:
      - org.gnome.Extensions
      - org.qbittorrent.qBittorrent
      - org.videolan.VLC

- name: Installing Other Applications
  become: yes
  dnf:
    name: "{{item}}"
    state: present
  loop:
    - vim
    - fira-code-fonts
    - gnome-tweaks