---
- name: Installing starship
  become: yes
  dnf:
    name: starship
    state: present

- name: Initializing starship
  shell: "printf 'eval \"$(starship init bash)\"' >> /home/{{ lookup('env', 'USER') }}/.bashrc"
