---
- name: Adding GPG key for VSCode
  become: yes
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: Adding VSCode Repository
  become: yes
  yum_repository:
    state: present
    file: vscode
    name: code
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: yes
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc

- name: Install VSCode
  become: yes
  dnf:
    state: latest
    name: code
