---
- name: Configure git
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    scope: global
  loop:
    - { name: init.defaultBranch, value: main }
    - { name: user.name, value: "{{ name }}" }
    - { name: user.email, value: "{{ email }}" }

- name: Generating SSH Keys
  community.crypto.openssh_keypair:
    type: ed25519
    comment: "{{ email }}"
    path: "/home/{{ lookup('env', 'USER') }}/.ssh/github"

- name: Starting SSH agent
  shell: 'eval "$(ssh-agent -s)"'

- name: Adding Key to SSH agent
  shell: "ssh-add /home/{{ lookup('env', 'USER') }}/.ssh/github"
