---
- include: update_status.yml
  vars:
    text: Personalizing
- include_tasks: install_theme.yml
- include_tasks: install_icon_theme.yml
- include_tasks: install_blue_matrix_theme.yml
- include_tasks: set_padding.yml
- include_tasks: configure_keybindings.yml
- include_tasks: configure_git.yml
- include_tasks: set_wallpaper.yml
- include_tasks: set_favourite_apps.yml

- name: Writing post installation commands to clean up in .profile
  shell: "printf '\nrm /home/{{ lookup('env', 'USER') }}/.profile\nmv /home/{{ lookup('env', 'USER') }}/profile_backup /home/{{ lookup('env', 'USER') }}/.profile' >> /home/{{ lookup('env', 'USER') }}/.profile"
