---
- name: Determining Shell Version
  shell: gnome-shell --version | grep -Eo '[0-9].*'
  register: shell_version


- name: Fetching Downloads links
  uri:
    url: "https://extensions.gnome.org/extension-info/?pk={{ item }}&shell_version={{ shell_version.stdout }}"
    method: GET
    return_content: yes
  loop: "{{ extensions }}"
  register: api

- name: Creating Installation Directory
  file:
    path: "/home/{{ lookup('env', 'USER') }}/.local/share/gnome-shell/extensions/{{ item.json.uuid }}"
    state: directory
    mode: '0755'
  loop: "{{ api.results }}"

- name: Downloading Extensions
  unarchive:
    remote_src: yes
    src: "https://extensions.gnome.org/{{ item.json.download_url }}"
    dest: "/home/{{ lookup('env', 'USER') }}/.local/share/gnome-shell/extensions/{{ item.json.uuid }}"
  loop: "{{ api.results }}"

- name: Creating Extension installer in .profile for next login
  shell: "printf '\ngnome-extensions enable {{ item.json.uuid }}' >> /home/{{ lookup('env', 'USER') }}/.profile"
  loop: "{{ api.results }}"
